// Build-time content pipeline: reads in-repo markdown blog posts, renders them to
// HTML, and emits a typed TS module the app imports. Running at build keeps the
// runtime free of markdown parsing and ensures every post is prerendered.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { marked } from 'marked';

const here = dirname(fileURLToPath(import.meta.url));
const BLOG_DIR = join(here, '..', 'src', 'app', 'content', 'blog');
const OUT_FILE = join(BLOG_DIR, 'generated-posts.ts');

marked.setOptions({ mangle: false, headerIds: false });

function readingMinutes(text) {
  const words = text.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 200));
}

// YAML auto-parses unquoted ISO dates into Date objects; normalize to yyyy-mm-dd (UTC).
function isoDate(d) {
  if (d instanceof Date) return d.toISOString().slice(0, 10);
  return String(d ?? '').slice(0, 10);
}

const files = (await readdir(BLOG_DIR)).filter((f) => f.endsWith('.md'));

const posts = [];
for (const file of files) {
  const raw = await readFile(join(BLOG_DIR, file), 'utf8');
  const { data, content } = matter(raw);
  const html = marked.parse(content);
  posts.push({
    slug: data.slug ?? basename(file, '.md'),
    title: data.title ?? '',
    description: data.description ?? '',
    date: isoDate(data.date),
    ...(data.updated ? { updated: isoDate(data.updated) } : {}),
    category: data.category ?? 'Articles',
    readingMinutes: readingMinutes(content),
    related: Array.isArray(data.related) ? data.related : [],
    html,
  });
}

// Newest first.
posts.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

const banner = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.\n// Source: src/app/content/blog/*.md\n`;
const body = `import { BlogPost } from './blog.types';\n\nexport const BLOG_POSTS: BlogPost[] = ${JSON.stringify(
  posts,
  null,
  2,
)};\n`;

await writeFile(OUT_FILE, banner + body, 'utf8');
console.log(`build-content: wrote ${posts.length} post(s) to generated-posts.ts`);
